version: '3.8'

services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.network=traefik_network"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik_network
    restart: always

  phonebook:
    build: .
    container_name: phonebook-app
    environment:
      - DB_HOST=192.168.100.26
      - DB_USER=root
      - DB_PASSWORD=Qpz1zX1
      - DB_NAME=phone_book
      - FLASK_ENV=production
    volumes:
      - ./static:/app/static
    restart: unless-stopped
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phonebook.rule=Host(`phonebook.aftabnetad.com`)"
      - "traefik.http.routers.phonebook.entrypoints=web"
      - "traefik.http.services.phonebook.loadbalancer.server.port=5000"
      - "traefik.docker.network=traefik_network"

networks:
  traefik_network:
    driver: bridge
